name: Hourly AQHI Grid

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            pandas \
            geopandas \
            scipy \
            numpy \
            folium \
            branca \
            shapely \
            matplotlib
      - name: Run preprocessing
        run: python AQHI_idw.py
      - name: Commit & push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data/AQHI_idw.csv
          git add data/AQHI_grid.geojson
          git commit -m "Update AQHI IDW grid (CSV + GeoJSON)"
          git push
                # 5) Commit & push the generated HTML back to the repo
      - name: Commit and Push HTML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add aqhi_map.html
          git commit -m "Update aqhi_map.html"
          git push
