name: Fetch Last 6h Data

# Schedule to run once every day at 04:00 UTC (which is 10:00 PM MST or whatever you prefer)
on:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. Pull down your repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Set up Python (choose the version you need)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install required packages
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      # 4. Run your Python script
      - name: Run fetch_last6h.py
        run: |
          python fetch_last6h.py

      # 5. Commit the updated CSV back into the repo (if it changed)
      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/_last6h.csv
          git diff --quiet --exit-code || git commit -m "chore: update _last6h.csv"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
