name: Fetch Last 6h Data

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run fetch_last6h.py
        run: python fetch_last6h.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/last6h.csv
          git commit --allow-empty -m "chore: update last6h.csv"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
